package goanalysis

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	gocmp "github.com/google/go-cmp/cmp"
	"golang.org/x/tools/go/analysis"

	"github.com/zchee/goimports-rereviser/v4/reviser"
)

type analyzerDiagnostic struct {
	Message string
	Line    int
	Column  int
}

func TestAnalyzerRun(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		source           string
		localPkgPrefixes string
		options          []reviser.SourceFileOption
		want             []analyzerDiagnostic
	}{
		"already formatted file reports no diagnostics": {
			source: `package sample

import (
	"fmt"

	"example.com/project/internal/foo"
)

var _ = fmt.Println
var _ = foo.Name
`,
		},
		"reordered imports reports one diagnostic": {
			source: `package sample

import (
	"example.com/project/internal/foo"
	"fmt"
)

var _ = fmt.Println
var _ = foo.Name
`,
			want: []analyzerDiagnostic{{
				Message: errMessage,
				Line:    3,
				Column:  9,
			}},
		},
		"generated file without skip option is characterized as reportable": {
			source: `// Code generated by test DO NOT EDIT.
package sample

import (
	"example.com/project/internal/foo"
	"fmt"
)

var _ = fmt.Println
var _ = foo.Name
`,
			want: []analyzerDiagnostic{{
				Message: errMessage,
				Line:    6,
				Column:  3,
			}},
		},
		"generated file with skip option reports no diagnostics": {
			source: `// Code generated by test DO NOT EDIT.
package sample

import (
	"example.com/project/internal/foo"
	"fmt"
)

var _ = fmt.Println
var _ = foo.Name
`,
			options: []reviser.SourceFileOption{reviser.WithSkipGeneratedFile},
		},
		"single cgo import reports no diagnostics": {
			source: `package sample

/*
#include <stdlib.h>
*/
import "C"

func f() {}
`,
		},
		"company prefix grouping reports one diagnostic": {
			source: `package sample

import (
	"example.com/project/internal/foo"
	"example.com/company/lib"
	"fmt"
	"github.com/acme/ext"
)

var _ = fmt.Println
var _ = lib.Name
var _ = ext.Name
var _ = foo.Name
`,
			localPkgPrefixes: "example.com/company",
			want: []analyzerDiagnostic{{
				Message: errMessage,
				Line:    3,
				Column:  9,
			}},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			got := runAnalyzer(t, tt.source, tt.localPkgPrefixes, tt.options...)
			if diff := gocmp.Diff(tt.want, got); diff != "" {
				t.Errorf("diagnostics mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func runAnalyzer(t *testing.T, source, localPkgPrefixes string, options ...reviser.SourceFileOption) []analyzerDiagnostic {
	t.Helper()

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/project\n\ngo 1.26\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	filePath := filepath.Join(dir, "sample.go")
	if err := os.WriteFile(filePath, []byte(source), 0o644); err != nil {
		t.Fatalf("write sample.go: %v", err)
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, []byte(source), parser.ParseComments)
	if err != nil {
		t.Fatalf("parse source: %v", err)
	}

	analyzer := NewAnalyzer(flag.NewFlagSet(t.Name(), flag.ContinueOnError), localPkgPrefixes, options...)
	var diagnostics []analyzerDiagnostic
	_, err = analyzer.Run(&analysis.Pass{
		Fset:  fset,
		Files: []*ast.File{file},
		Report: func(diagnostic analysis.Diagnostic) {
			position := fset.Position(diagnostic.Pos)
			diagnostics = append(diagnostics, analyzerDiagnostic{
				Message: diagnostic.Message,
				Line:    position.Line,
				Column:  position.Column,
			})
		},
	})
	if err != nil {
		t.Fatalf("run analyzer: %v", err)
	}

	return diagnostics
}
