package reviser

import (
	"os"
	"strings"
	"testing"

	"golang.org/x/tools/txtar"
)

// parseTestArchive extracts input and expected output from a txtar archive.
func parseTestArchive(t *testing.T, archive string) (input, want []byte) {
	t.Helper()

	// Clear caches before each test to prevent pollution between tests
	clearTestCaches()

	ar := txtar.Parse([]byte(archive))
	for _, f := range ar.Files {
		switch f.Name {
		case "input.go":
			input = f.Data
		case "want.go":
			want = f.Data
		}
	}
	if input == nil {
		t.Fatal("txtar archive must contain input.go")
	}
	return input, want
}

func TestSourceFile_Fix(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "success with comments",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/v4/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/v4/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with auto-generated",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Code generated by some tool
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
// Code generated by some tool
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with auto-generated",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Code generated by some tool, DO NOT EDIT.
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
// Code generated by some tool, DO NOT EDIT.
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with directive",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt"
	"crypto/sha1" //nolint:gosec // Usage is for collision avoidance not security.
)

func main() {
	s := sha1.New()
	s.Write([]byte("example"))
	fmt.Printf("%x\n", s.Sum(nil))
}
-- want.go --
package testdata

import (
	"crypto/sha1" //nolint:gosec // Usage is for collision avoidance not security.
	"fmt"
)

func main() {
	s := sha1.New()
	s.Write([]byte("example"))
	fmt.Printf("%x\n", s.Sum(nil))
}
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with std & project deps",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"


)

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with std & third-party deps",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
"log"

"bytes"

"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with std deps only",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
		
import (
"log"

"bytes"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "success with single std deps only",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import "log"

// nolint:gomnd
-- want.go --
package testdata

import "log"

// nolint:gomnd
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "success with third-party deps only",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "success with single third-party deps",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import "golang.org/x/tools/go/packages"

// nolint:gomnd
-- want.go --
package testdata

import "golang.org/x/tools/go/packages"

// nolint:gomnd
`,
			wantChange: false,
			wantErr:    false,
		},

		{
			name:        "success with project deps only",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

)

// nolint:gomnd
-- want.go --
package testdata

import (
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with preserved doc comment for import",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt"


	// test
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"fmt"

	// test
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with comment for import",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"github.com/zchee/goimports-rereviser/testdata/innderpkg" // test1
	
	"fmt" //test2
	// this should be skipped
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"fmt" //test2

	"github.com/zchee/goimports-rereviser/testdata/innderpkg" // test1
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with no changes",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "success no changes by imports and comments",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"context"
	"database/sql"
	"fmt"

	_ "github.com/lib/pq" // configure database/sql with postgres driver
	"go.uber.org/fx"
	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/pkg/somepkg"
)
-- want.go --
package testdata

import (
	"context"
	"database/sql"
	"fmt"

	_ "github.com/lib/pq" // configure database/sql with postgres driver
	"go.uber.org/fx"
	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/pkg/somepkg"
)
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "success with multiple import statements",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

	import "sync" //test comment
	import "testing"

	// yolo
	import "fmt"


	// not sure why this is here but we shall find out soon enough
	import "io"
-- want.go --
package testdata

import (
	"fmt"
	"io"
	"sync" //test comment
	"testing"
)
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "preserves cgo import",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/cgo_example.go",
			archive: `
-- input.go --
package testdata

/*
#include <stdlib.h>
*/
import "C"

import (
	"errors"
	"fmt"
)
-- want.go --
package testdata

/*
#include <stdlib.h>
*/
import "C"

import (
	"errors"
	"fmt"
)
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "preserves cgo import with single std deps",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/cgo_example.go",
			archive: `
-- input.go --
package testdata

/*
#include <stdlib.h>
*/
import "C"

import "errors"
-- want.go --
package testdata

/*
#include <stdlib.h>
*/
import "C"

import "errors"
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "preserves cgo import with single import",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/cgo_example.go",
			archive: `
-- input.go --
package testdata

/*
#include <stdlib.h>
*/
import "C"
-- want.go --
package testdata

/*
#include <stdlib.h>
*/
import "C"
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "preserves cgo import even when reordering",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/cgo_example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt"
	"errors"
)

/*
#include <stdlib.h>
*/
import "C"

import "errors"
-- want.go --
package testdata

import (
	"errors"
	"fmt"
)

/*
#include <stdlib.h>
*/
import "C"
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "try to read from stdin",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    StandardInput,
			archive: `
-- input.go --
`,
			wantChange: false,
			wantErr:    true,
		},
		{
			name:        "error with non-existent file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdatax/does-not-exist.go",
			archive: `
-- input.go --
`,
			wantChange: false,
			wantErr:    true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file for normal cases
			filePath := tt.filePath
			if filePath != StandardInput && !strings.Contains(filePath, "does-not-exist") {
				filePath = "./testdata/example.go"
				if err := os.WriteFile(filePath, input, 0o644); err != nil {
					t.Fatalf("failed to write test file: %v", err)
				}
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix()

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v\ninput len=%d, got len=%d, want len=%d", hasChange, tt.wantChange, len(input), len(got), len(want))
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithImportsOrder(t *testing.T) {
	tests := []struct {
		name         string
		projectName  string
		filePath     string
		archive      string
		importsOrder string
		wantChange   bool
		wantErr      bool
	}{
		{
			name:        "success with default order",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			importsOrder: "",
			wantChange:   true,
			wantErr:      false,
		},
		{
			name:        "success std,general,company,project",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			importsOrder: "std,general,company,project",
			wantChange:   true,
			wantErr:      false,
		},
		{
			name:        "success project,company,general,std",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"golang.org/x/tools/go/packages"

	"bytes"
	"log"
)

// nolint:gomnd
`,
			importsOrder: "project,company,general,std",
			wantChange:   true,
			wantErr:      false,
		},
		{
			name:        "success project,company,general,std,blanked,dotted",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	. "io"

	"golang.org/x/tools/go/packages"

	_ "fmt"
)

// nolint:gomnd
-- want.go --
package testdata

import (
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"golang.org/x/tools/go/packages"

	"bytes"
	"log"

	_ "fmt"

	. "io"
)

// nolint:gomnd
`,
			importsOrder: "project,company,general,std,blanked,dotted",
			wantChange:   true,
			wantErr:      false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			order, err := StringToImportsOrders(tt.importsOrder)
			if err != nil {
				t.Fatalf("failed to parse imports order: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithImportsOrder(order))

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithRemoveUnusedImports(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "remove unused import",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt" //fmt package
	"golang.org/x/tools/go/packages" //custom package
)

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt" //fmt package
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "remove unused import with alias",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt" //fmt package
	p "golang.org/x/tools/go/packages" //p package
)

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt" //fmt package
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "use loaded import but not used",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt" //fmt package
	_ "golang.org/x/tools/go/packages" //custom package
)

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt" //fmt package

	_ "golang.org/x/tools/go/packages" //custom package
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "success with comments before imports",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Some comments are here
package testdata

// test
import (
	"fmt" //fmt package
	_ "golang.org/x/tools/go/packages" //custom package
)

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
// Some comments are here
package testdata

// test
import (
	"fmt" //fmt package

	_ "golang.org/x/tools/go/packages" //custom package
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "success without imports",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Some comments are here
package testdata

// OutputDir the output directory where the built version of Authelia is located.
var OutputDir = "dist"

// DockerImageName the official name of Authelia docker image.
var DockerImageName = "authelia/authelia"

// IntermediateDockerImageName local name of the docker image.
var IntermediateDockerImageName = "authelia:dist"

const masterTag = "master"
const stringFalse = "false"
const stringTrue = "true"
const suitePathPrefix = "PathPrefix"
const webDirectory = "web"
-- want.go --
// Some comments are here
package testdata

// OutputDir the output directory where the built version of Authelia is located.
var OutputDir = "dist"

// DockerImageName the official name of Authelia docker image.
var DockerImageName = "authelia/authelia"

// IntermediateDockerImageName local name of the docker image.
var IntermediateDockerImageName = "authelia:dist"

const masterTag = "master"
const stringFalse = "false"
const stringTrue = "true"
const suitePathPrefix = "PathPrefix"
const webDirectory = "web"
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        "cleanup empty import block",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Some comments are here
package testdata

import (
	"fmt"
)

// nolint:gomnd
func main(){
}
-- want.go --
// Some comments are here
package testdata

// nolint:gomnd
func main() {
}
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "skip blanked and dotted import names",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Some comments are here
package testdata

import (
	_ "fmt"
	. "io"
)

// nolint:gomnd
func main() {
}
-- want.go --
// Some comments are here
package testdata

import (
	_ "fmt"
	. "io"
)

// nolint:gomnd
func main() {
}
`,
			wantChange: false,
			wantErr:    false,
		},
		{
			name:        `success with "C"`,
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
/*
#cgo CFLAGS: -I
#cgo LDFLAGS: -L
#include <stdio.h>
#include <stdlib.h>
*/
import "C"
import(
	"fmt"
	"golang.org/x/tools/go/packages"
	"strconv"
)

func main(){
	_ = strconv.Itoa(1)
	fmt.Println(pg.In([]string{"test"}))
}
-- want.go --
package testdata

/*
#cgo CFLAGS: -I
#cgo LDFLAGS: -L
#include <stdio.h>
#include <stdlib.h>
*/
import "C"
import (
	"fmt"
	"strconv"
)

func main() {
	_ = strconv.Itoa(1)
	fmt.Println(pg.In([]string{"test"}))
}
`,
			wantChange: true,
			wantErr:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithRemovingUnusedImports)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithAliasForVersionSuffix(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "success with golang.org/x/tools/go/packages",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
import(
	"fmt"
	"golang.org/x/tools/go/packages"
	"strconv"
)

func main(){
	_ = strconv.Itoa(1)
	fmt.Println(pg.In([]string{"test"}))
}
-- want.go --
package testdata

import (
	"fmt"
	"strconv"

	"golang.org/x/tools/go/packages"
)

func main() {
	_ = strconv.Itoa(1)
	fmt.Println(pg.In([]string{"test"}))
}
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        `success with "C"`,
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
/*
#cgo CFLAGS: -I
#cgo LDFLAGS: -L
#include <stdio.h>
#include <stdlib.h>
*/
import "C"
import(
	"fmt"
	"golang.org/x/tools/go/packages"
	"strconv"
)

func main(){
	_ = strconv.Itoa(1)
	fmt.Println(pg.In([]string{"test"}))
}
-- want.go --
package testdata

/*
#cgo CFLAGS: -I
#cgo LDFLAGS: -L
#include <stdio.h>
#include <stdlib.h>
*/
import "C"
import (
	"fmt"
	"strconv"

	"golang.org/x/tools/go/packages"
)

func main() {
	_ = strconv.Itoa(1)
	fmt.Println(pg.In([]string{"test"}))
}
`,
			wantChange: true,
			wantErr:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithUsingAliasForVersionSuffix)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithRemovingUnusedImportsAndAlias(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "removes unused import and sets alias",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `-- input.go --
package testdata
import(
	"fmt"
	"github.com/zchee/goimports-rereviser/v4/testdata/aliaspkg/v2"
	"strconv"
)

func main(){
	fmt.Println(aliaspkg.Value())
}
-- want.go --
package testdata

import (
	"fmt"

	aliaspkg "github.com/zchee/goimports-rereviser/v4/testdata/aliaspkg/v2"
)

func main() {
	fmt.Println(aliaspkg.Value())
}
`,
			wantChange: true,
			wantErr:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			filePath := tt.filePath
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}
			t.Cleanup(func() {
				_ = os.Remove(filePath)
			})

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(
				WithRemovingUnusedImports,
				WithUsingAliasForVersionSuffix,
			)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithLocalPackagePrefixes(t *testing.T) {
	tests := []struct {
		name             string
		projectName      string
		filePath         string
		archive          string
		localPkgPrefixes string
		wantChange       bool
		wantErr          bool
	}{
		{
			name:        "group local packages",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt" //fmt package
	"golang.org/x/tools/go/packages" //custom package
	"github.com/zchee/goimports-rereviser/pkg"
	"goimports-rereviser/pkg"
)

/*
#include <stdlib.h>
*/
import "C"

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt" //fmt package

	"golang.org/x/tools/go/packages" //custom package

	"goimports-rereviser/pkg"

	"github.com/zchee/goimports-rereviser/pkg"
)

/*
#include <stdlib.h>
*/
import "C"

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			localPkgPrefixes: "goimports-rereviser",
			wantChange:       true,
			wantErr:          false,
		},
		{
			name:        "group local packages",
			projectName: "goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt" // fmt package
	"golang.org/x/tools/go/packages" //custom package
	"github.com/zchee/goimports-rereviser/pkg"
	"goimports-rereviser/pkg"
)
// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt" // fmt package

	"golang.org/x/tools/go/packages" //custom package

	"github.com/zchee/goimports-rereviser/pkg"

	"goimports-rereviser/pkg"
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			localPkgPrefixes: "github.com/zchee/goimports-rereviser",
			wantChange:       true,
			wantErr:          false,
		},
		{
			name:        "group local packages separately from project files",
			projectName: "github.com/zchee/goimports-rereviser/code/thispkg",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt"
	"github.com/3rdparty/pkg"
	"github.com/zchee/goimports-rereviser/code/foopkg"
	"github.com/zchee/goimports-rereviser/code/otherpkg"
	"github.com/zchee/goimports-rereviser/code/thispkg/stuff"
	"github.com/zchee/goimports-rereviser/code/thispkg/morestuff"
)

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt"

	"github.com/3rdparty/pkg"

	"github.com/zchee/goimports-rereviser/code/foopkg"
	"github.com/zchee/goimports-rereviser/code/otherpkg"

	"github.com/zchee/goimports-rereviser/code/thispkg/morestuff"
	"github.com/zchee/goimports-rereviser/code/thispkg/stuff"
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			localPkgPrefixes: "github.com/zchee/goimports-rereviser/code",
			wantChange:       true,
			wantErr:          false,
		},
		{
			name:        "check without local packages",
			projectName: "github.com/zchee/goimports-rereviser/code/thispkg",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"fmt"
	"github.com/3rdparty/pkg"
	"github.com/zchee/goimports-rereviser/code/foopkg"
	"github.com/zchee/goimports-rereviser/code/otherpkg"
	"github.com/zchee/goimports-rereviser/code/thispkg/stuff"
	"github.com/zchee/goimports-rereviser/code/thispkg/morestuff"
)

// nolint:gomnd
func main(){
  _ = fmt.Println("test")
}
-- want.go --
package testdata

import (
	"fmt"

	"github.com/3rdparty/pkg"
	"github.com/zchee/goimports-rereviser/code/foopkg"
	"github.com/zchee/goimports-rereviser/code/otherpkg"

	"github.com/zchee/goimports-rereviser/code/thispkg/morestuff"
	"github.com/zchee/goimports-rereviser/code/thispkg/stuff"
)

// nolint:gomnd
func main() {
	_ = fmt.Println("test")
}
`,
			localPkgPrefixes: "",
			wantChange:       true,
			wantErr:          false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithCompanyPackagePrefixes(tt.localPkgPrefixes))

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithFormat(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "success",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
type SomeStruct struct{}
type SomeStruct1 struct{}
// SomeStruct2 comments
type SomeStruct2 struct{}
func (s *SomeStruct2) test() {}
func test(){}
func test1(){}
-- want.go --
package testdata

type SomeStruct struct{}

type SomeStruct1 struct{}

// SomeStruct2 comments
type SomeStruct2 struct{}

func (s *SomeStruct2) test() {}

func test() {}

func test1() {}
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "success with comments",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
// test -  test comment
func test(){}
// test1 -  test comment
func test1(){}
-- want.go --
package testdata

// test -  test comment
func test() {}

// test1 -  test comment
func test1() {}
`,
			wantChange: true,
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithCodeFormatting)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithSkipGeneratedFile(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Code generated by some tool
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
// Code generated by some tool
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Code generated by some tool, DO NOT EDIT.
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
// Code generated by some tool, DO NOT EDIT.
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
`,
			wantChange: false,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
// Code generated by some tool DO NOT EDIT.
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
// Code generated by some tool DO NOT EDIT.
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
`,
			wantChange: false,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
/*
Other comment or copyright
*/

// Code generated by some tool DO NOT EDIT.

package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
/*
Other comment or copyright
*/

// Code generated by some tool DO NOT EDIT.

package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
`,
			wantChange: false,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
/*
Other comment or copyright
*/

package testdata

// Code generated by some tool DO NOT EDIT.

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
/*
Other comment or copyright
*/

package testdata

// Code generated by some tool DO NOT EDIT.

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

// Code generated by some tool DO NOT EDIT.

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// nolint:gomnd
-- want.go --
package testdata

// Code generated by some tool DO NOT EDIT.

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// Code generated by some tool DO NOT EDIT.
// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// Code generated by some tool DO NOT EDIT.
// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},

		{
			name:        "success with generated file",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata

import (
	"log"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	"bytes"

	"golang.org/x/tools/go/packages"
)

// Inner comment

// Code generated by some tool DO NOT EDIT.

// nolint:gomnd
-- want.go --
package testdata

import (
	"bytes"
	"log"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)

// Inner comment

// Code generated by some tool DO NOT EDIT.

// nolint:gomnd
`,
			wantChange: true,
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithSkipGeneratedFile)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}

func TestSourceFile_Fix_WithSeparatedNamedImports(t *testing.T) {
	tests := []struct {
		name        string
		projectName string
		filePath    string
		archive     string
		wantChange  bool
		wantErr     bool
	}{
		{
			name:        "simple",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
import (
	"fmt"
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
	"bytes"
	"golang.org/x/tools/go/packages"
)
-- want.go --
package testdata

import (
	"bytes"
	"fmt"

	"golang.org/x/tools/go/packages"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "named",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
import (
	"fmt"
	second "github.com/zchee/goimports-rereviser/testdata/secondpkg"
	by "bytes"
	js "encoding/json"
	"golang.org/x/tools/go/packages"
	er "golang.org/x/errors"
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)
-- want.go --
package testdata

import (
	"fmt"

	by "bytes"
	js "encoding/json"

	"golang.org/x/tools/go/packages"

	er "golang.org/x/errors"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	second "github.com/zchee/goimports-rereviser/testdata/secondpkg"
)
`,
			wantChange: true,
			wantErr:    false,
		},
		{
			name:        "named with comments",
			projectName: "github.com/zchee/goimports-rereviser",
			filePath:    "./testdata/example.go",
			archive: `
-- input.go --
package testdata
import (
	"fmt" //fmt package
	second "github.com/zchee/goimports-rereviser/testdata/secondpkg" //secondpkg package
	by "bytes"
	js "encoding/json"
	"golang.org/x/tools/go/packages" //packages package
	er "golang.org/x/errors"
	"github.com/zchee/goimports-rereviser/testdata/innderpkg"
)
-- want.go --
package testdata

import (
	"fmt" //fmt package

	by "bytes"
	js "encoding/json"

	"golang.org/x/tools/go/packages" //packages package

	er "golang.org/x/errors"

	"github.com/zchee/goimports-rereviser/testdata/innderpkg"

	second "github.com/zchee/goimports-rereviser/testdata/secondpkg" //secondpkg package
)
`,
			wantChange: true,
			wantErr:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			input, want := parseTestArchive(t, tt.archive)

			// Write input to temp file
			filePath := "./testdata/example.go"
			if err := os.WriteFile(filePath, input, 0o644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}

			got, _, hasChange, err := NewSourceFile(tt.projectName, filePath).Fix(WithSeparatedNamedImports)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if hasChange != tt.wantChange {
				t.Errorf("hasChange = %v, want %v", hasChange, tt.wantChange)
			}

			if want != nil && string(got) != string(want) {
				t.Errorf("output mismatch:\ngot:\n%s\n\nwant:\n%s", got, want)
			}
		})
	}
}
