name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-26-intel] # , windows-latest

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Get dependencies
        run: |
          go mod download
          go get github.com/go-pg/pg/v9

      - name: Test
        run: |
          go test -race -count=1 -shuffle=on -cover -covermode=atomic -coverpkg=./... -coverprofile=coverage.out -tags='osusergo,netgo,static' -ldflags='-s -w' ./...

      - name: coverage
        uses: codecov/codecov-action@v6
        with:
          use_oidc: true
          files: ./coverage.out
          flags: ${{ runner.os }}
          fail_ci_if_error: false
          verbose: true
